config/routes.rb
Vestibule::Application.routes.draw do
  resources :users, :only => [:show, :edit, :update]
  resources :proposals, :except => [:destroy] do
    resources :suggestions, :only => [:create]
    member do
      post :withdraw
    end
  end
  resources :selections, :only => [:index, :create, :destroy]

  anyone_can :see, :motivation do
    match "/motivation", :to => "home#motivation", :as => "motivation"
  end
  anyone_can :add, :motivation do
    match "/my-motivation", :to => "home#my_motivation", :as => "complete_motivation"
  end
  match "/about", :to => "home#about", :as => "about"
  match "/anonymous-proposals", :to => "home#anonymous_proposals", :as => "anonymous_proposals"
  match "/the-vestibule-process", :to => "home#the_vestibule_process", :as => "the_vestibule_process"

  match "/dashboard", :to => "dashboard#index"

  match "/auth/github/callback", :to => "github_authentication#callback"
  match "/logout", :to => "github_authentication#logout", :as => "logout"

  root :to => "home#index"
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :proposer, :class_name => 'User'
  has_many :suggestions

  acts_as_voteable

  validates :title, :presence => true

  # This allows us to do @proposal.impression_count
  # and other stuff from the 'impressionist' gem.
  is_impressionable counter_cache: { column_name: :impressions_counter_cache }

  scope :without_suggestions_from, lambda { |user|
    if user.suggestions.any?
      where('id NOT IN (?)', user.suggestions.map{ |s| s.proposal_id }.uniq)
    end
  }

  scope :without_votes_from, lambda { |user|
    voted_by_user = user.votes.where(voteable_type: 'Proposal')
    if voted_by_user.any?
      where('id NOT IN (?)', voted_by_user.map{ |s| s.voteable_id }.uniq)
    end
  }

  scope :not_proposed_by, lambda { |user|
    where('proposer_id != ?', user.id)
  }

  scope :active, where(withdrawn: false)
  scope :withdrawn, where(withdrawn: true)

  after_create :update_proposer_score

  def last_modified
    new_suggestions.any? ? new_suggestions.maximum(:updated_at) : last_modified_by_proposer
  end

  def proposed_by?(user)
    proposer == user
  end

  def new_suggestions
    suggestions.after(last_modified_by_proposer)
  end

  def published?
    !withdrawn
  end

  def withdraw!
    update_attribute(:withdrawn, true)
  end

  def republish!
    update_attribute(:withdrawn, false)
  end

  private

  def last_modified_by_proposer
    [suggestions.by(proposer).maximum(:updated_at), updated_at].compact.max
  end

  def update_proposer_score
    proposer.save
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  impressionist :actions=> [:show]

  respond_to :html
  respond_to :rss, :only => [:index, :show]

  def index
    authorize! :read, Proposal

    @withdrawn_proposals = Proposal.withdrawn.all
    @proposals = Proposal.active.order('created_at desc').all

    respond_with @proposals
  end

  def show
    @proposal = Proposal.find(params[:id])
    authorize! :read, @proposal

    @suggestion = Suggestion.new if can?(:create, Suggestion)

    respond_with @proposal
  end

  def new
    @proposal = Proposal.new({:proposer => current_user}.merge(params[:proposal] || {}))
    authorize! :new, @proposal
  end

  def create
    @proposal = Proposal.new({:proposer => current_user}.merge(params[:proposal] || {}))
    authorize! :create, @proposal

    if @proposal.save
      redirect_to proposals_path
    else
      render :new
    end
  end

  def edit
    @proposal = Proposal.find(params[:id])
    authorize! :edit, @proposal
  end

  def update
    @proposal = Proposal.find(params[:id])
    authorize! :update, @proposal

    if @proposal.update_attributes(params[:proposal])
      redirect_to proposal_path(@proposal)
    else
      render :edit
    end
  end

  def withdraw
    @proposal = Proposal.find(params[:id])
    authorize! :withdraw, @proposal

    @proposal.withdraw!
    redirect_to proposal_path(@proposal), alert: "Your proposal has been withdrawn"
  end

  def republish
    @proposal = Proposal.find(params[:id])
    authorize! :republish, @proposal

    @proposal.republish!
    redirect_to proposal_path(@proposal), notice: "Your proposal has been republished"
  end

  def vote
    @proposal = Proposal.find(params[:id])
    authorize! :vote, @proposal

    if params[:vote] == 'clear'
      current_user.unvote_for(@proposal)
      flash[:notice] = 'Your vote has been cleared. Remember to come back to vote again once you are sure!'
    else
      current_user.vote(@proposal, :direction => params[:vote], :exclusive => true )
      flash[:notice] = 'Thank you for casting your vote. Your vote has been captured!'
    end

    redirect_to proposal_path(@proposal)
  end
end

app/views/proposals/_form.html.erb
<%= simple_form_for @proposal do |f| %>
  <% if notification = f.error_notification %>
    <div class="alert alert-error fade in">
      <%= notification %>
    </div>
  <% end %>
  <%= f.input :title %>
  <%= f.input :description, as: :markdown %>
  <%= f.button :submit, f.object.new_record? ? t("vestibule.proposal.submit") : t("vestibule.proposal.update"), class: "btn btn-primary" %>
<% end %>

app/views/proposals/edit.html.erb
<%= page_title t("vestibule.proposal.edit") %>
<%= render "form" %>

app/views/proposals/index.html.erb
<section>
  <%= page_title t("vestibule.proposals.title") %>
  <%= user_can(:make, :proposal) do %>
    <div class="action">
      <%= link_to t("vestibule.proposals.propose.one"), new_proposal_path, class: "btn btn-primary btn-large" %>
    </div>
  <% end %>

  <ul class="proposals">
    <% for proposal in @proposals %>
      <%= content_tag_for :li, proposal do %>
        <%= link_to proposal.title, proposal %>
        <span class="age"><%= proposal_update_information proposal %></span>
      <% end %>
    <% end %>
  </ul>
</section>

<% if @withdrawn_proposals.any? %>
<section>
  <p><%= t "vestibule.proposals.withdrawn" %></p>
  <ul class="proposals">
    <% for proposal in @withdrawn_proposals %>
      <%= content_tag_for :li, proposal do %>
        <%= link_to proposal.title, proposal %>
        <span class="age"><%= proposal_update_information proposal %></span>
      <% end %>
    <% end %>
  </ul>
</section>
<% end %>

<% content_for :head do %>
  <%= auto_discovery_link_tag :rss, :format => :rss %>
<% end %>

app/views/proposals/new.html.erb
<p class="well"><%=t "vestibule.proposal.pitch.html", :link => link_to(t("vestibule.proposal.pitch.link"), the_vestibule_process_path) %></p>

<%= page_title t("vestibule.proposal.title") %>

<p><%=t "vestibule.proposal.anonymous.html", :link => link_to(t("vestibule.proposal.anonymous.link"), anonymous_proposals_path) %></p>

<%= render "form" %>

app/views/proposals/show.html.erb
<div class="row">
  <div class="span6">
    <div id="proposal">
      <%= proposal_div(@proposal) do %>
        <%= page_title @proposal.title %>
        <% if can_show_proposal_author_information?(@proposal) %>
          <p class="alert alert-notice"><%=t "vestibule.proposal.chosen", link: link_to(@proposal.proposer.name, @proposal.proposer) %></p>
        <% end %>

        <%= proposal_manipulation_actions(@proposal, current_user) %>
        <p class="age"><%= proposal_update_information @proposal %></p>

        <% if @proposal.withdrawn? %><h2 class="withdrawl_explanation"><%=t "vestibule.proposal.withdrawn" %></h2><% end %>
        <div class="description"><%= markdown @proposal.description %></div>
      <% end %>
    </div>
  </div>

  <div class="span5 offset1">
    <div id="suggestions">
      <h2><%=t "vestibule.proposal.suggestions.title" %></h2>
      <%= user_can(:make, :suggestion) do %>
        <% if current_user == @proposal.proposer %>
          <p><%=t "vestibule.proposal.suggestions.make.your" %></p>
        <% else %>
          <p><%=t "vestibule.proposal.suggestions.make.other" %></p>
        <% end %>

        <%= simple_form_for [@proposal, @suggestion] do |f| %>
          <% if notification = f.error_notification %>
            <div class="alert alert-error fade in">
              <%= notification %>
            </div>
          <% end %>

          <%= f.input :body, as: :markdown, input_html: {rows: 10} %>
          <%= f.button :submit, t("vestibule.proposal.suggestions.make.title"), class: "btn" %>
        <% end %>
      <% end %>

      <ul class="suggestions">
        <% @proposal.suggestions.latest.each do |suggestion| %>
          <%= content_tag_for(:li, suggestion) do %>
            <p class="author">
              <% if suggestion.author == @proposal.proposer %>
                <% if current_user == @proposal.proposer %>
                  <%=t "vestibule.proposal.suggestions.attribution.your" %>
                <% else %>
                  <%=t "vestibule.proposal.suggestions.attribution.proposal_author" %>
                <% end %>
              <% else %>
                <%=t("vestibule.proposal.suggestions.attribution.other", :suggestor => render('shared/user', :user => suggestion.author)).html_safe %>
              <% end %>
              <span class="age"><%= time_ago_in_words suggestion.updated_at %> ago</span>
            </p>
            <section class="body"><%= markdown suggestion.body %></section>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<% content_for :head do %>
  <%= auto_discovery_link_tag :rss, :format => :rss %>
<% end %>