config/routes.rb
Vestibule::Application.routes.draw do
  resources :users, :only => [:show, :edit, :update]
  resources :proposals, :except => [:destroy] do
    resources :suggestions, :only => [:create]
    member do
      post :withdraw
    end
  end
  resources :selections, :only => [:index, :create, :destroy]

  anyone_can :see, :motivation do
    match "/motivation", :to => "home#motivation", :as => "motivation"
  end
  anyone_can :add, :motivation do
    match "/my-motivation", :to => "home#my_motivation", :as => "complete_motivation"
  end
  match "/about", :to => "home#about", :as => "about"
  match "/anonymous-proposals", :to => "home#anonymous_proposals", :as => "anonymous_proposals"
  match "/the-vestibule-process", :to => "home#the_vestibule_process", :as => "the_vestibule_process"

  match "/dashboard", :to => "dashboard#index"

  match "/auth/github/callback", :to => "github_authentication#callback"
  match "/logout", :to => "github_authentication#logout", :as => "logout"

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= render_page_title %></title>
  <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
  <%= yield :head %>
  <%= render 'shared/analytics' %>
</head>
<body class="<%= body_class %>">
  <div class="container">
    <header>
      <div class="row">
        <div class="span5">
          <div class="brand">
            <h1><%= link_to t("vestibule.title"), root_path %></h1>
            <p><%= t("vestibule.strapline").html_safe %></p>
          </div>
        </div>

        <div class="span7">
          <ul class="nav nav-pills pull-right">
            <li<%= active_nav_class(about_path, anonymous_proposals_path, the_vestibule_process_path) %>><%= link_to "About", about_path %></li>
            <li<%= active_nav_class(proposals_path) %>><%= link_to t("vestibule.proposals.title"), proposals_path %></li>
            <%= anyone_can :add, :motivation do %>
            <li<%= active_nav_class(motivation_path, complete_motivation_path) %>><%= link_to t("vestibule.user.motivation.title"), motivation_path %></li>
            <% end %>
            <%= anyone_can(:see, :agenda) do %><li<%= active_nav_class(selections_path) %>><%= link_to t("vestibule.selections.agenda.nav_title"), selections_path %></li><% end %>
            <% if user_signed_in? -%>
              <li class="dropdown <%= 'active' if active_nav?(dashboard_path, user_path(current_user)) %>">
                <a class="dropdown-toggle"
                   data-toggle="dropdown"
                   href="#">
                  <%= current_user.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu pull-right">
                  <li<%= active_nav_class(dashboard_path) %>><%= link_to t("vestibule.dashboard.title"), dashboard_path %></li>
                  <li<%= active_nav_class(user_path(current_user)) %>><%= link_to t("vestibule.user.title"), user_path(current_user) %></li>
                  <%= user_can(:make, :selection) do %><li<%= active_nav_class(selections_path) %>><%= link_to t("vestibule.selections.title"), selections_path %></li><% end %>
                  <li><%= link_to "Sign out", logout_path %></li>
                </ul>
              </li>
            <% else -%>
              <li><%= link_to "Sign in with Github", "/auth/github" %></li>
            <% end -%>
          </ul>
        </div>
      </div>
    </header>

    <div class="row">
      <div class="span12">
        <section id="notices">
          <%= render "shared/notices" %>

          <%= anyone_can :add, :motivation do %>
          <% if remind_account_for_signup_reason -%>
          <div class="alert">
            <%=t("vestibule.user.motivation.missing.your", :link => link_to(t("vestibule.user.motivation.missing.link"), edit_user_path(current_user))).html_safe %>
          </div>
          <% end -%>
          <% end %>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="span12">
        <section id="content">
          <%= yield %>
        </section>
      </div>
    </div>
  </div>
</body>
</html>